### ISSUE TITLE
duplicate passRole in PolicyName: "Metaflow-Policy"

### ISSUE THREAD

**Issue by jwang01** [Netflix/metaflow-tools#10]
line 547 & line 562 appear to be duplicate 
             - Effect: "Allow"
                Action: 
                  - "iam:PassRole"
                Resource:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-*"

**Comment by savingoyal** [comment]
Thanks, @jwang01 for pointing the oversight. Created PR #11.
