### ISSUE TITLE
Have a nice standalone terraform module for Metaflow

### ISSUE THREAD

**Issue by oavdeev** [Netflix/metaflow-tools#27]
Right now we have a pretty good terraform config in https://github.com/Netflix/metaflow-tools/pull/26, however a couple things would make it even easier to use:

* Make all the generic bits like VPC resources separate and optional. Many orgs would already have VPC in place, so Metaflow terraform should play nicely with those. For example, imagine someone already using [terraform-aws-vpc](https://github.com/terraform-aws-modules/terraform-aws-vpc), and now they want to deploy Metaflow. 
* To extend on that, it would be great if Metaflow terraform was a standalone module that would be usable by just importing it from Github. I think we're 95% there, it is just some bits that need to be moved from `infra` to `metaflow`.
*  (I imagine Sagemaker stuff would still be optional and separate from the "main" module)

**Comment by kldavis4** [comment]
@GregHilstonHop & @oavdeev I have completed the modularization of the metaflow in the source project associated with #26 . As soon as its merged, I can get a PR up for this.
