### ISSUE TITLE
cfn template error

### ISSUE THREAD

**Issue by samarth70** [Netflix/metaflow-tools#31]
Template contains errors.: Template format error: YAML not well-formed. (line 103, column 65)
This error comes comes when I create  a stack.

**Comment by savingoyal** [comment]
@samarth70 Can you ensure that you were able to copy the template correctly? I haven't been able to reproduce the error so far. What were the options that you chose for your deployment?

**Comment by samarth70** [comment]
![image](https://user-images.githubusercontent.com/44370096/121839337-7cf0a200-ccf9-11eb-9e09-d122efc8e2ec.png)
I am not very familiar with the environment.This was the problem I got.

**Comment by savingoyal** [comment]
Aha - you need to copy and paste the yaml - https://raw.githubusercontent.com/Netflix/metaflow-tools/master/aws/cloudformation/metaflow-cfn-template.yml. Right now, your template is the HTML that contains the template.
