### ISSUE TITLE
Invalid bucket name.

### ISSUE THREAD

**Issue by ideivitcom** [Netflix/metaflow-tools#5]
Hi. 
Deploying Cloudformation template, and testing 05 tutorial,I get:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"). Retrying 7 more times..

The bucket name is created by the name of the stack. 
The arm is obtained as in the picture below
![image](https://user-images.githubusercontent.com/48516073/71354363-fcc20400-257b-11ea-9af7-15ad9fd175c4.png)

The arm is: arn:aws:s3:::stackmetaflow-metaflows3bucket-[REMOVED-BY-SECURITY]

I have configured the aws credentials (linux client usign aws2) as well as the bucket (metaflow configure aws)

What am I doing wrong?

**Comment by savingoyal** [comment]
Take a look at the output of the cloudformation stack. It contains all the variables you need to set when you type ‘metaflow configure aws’. Are you using metaflow v2.0.1?

**Comment by ideivitcom** [comment]
With the name given on outputs, works
![image](https://user-images.githubusercontent.com/48516073/71355264-c6d24f00-257e-11ea-9ef0-a1b715c3bace.png)

I'm using 2.0.0
Metaflow (2.0.0): More data science, less engineering

Regards!
