### ISSUE TITLE
Task crashed due to CannotPullContainerError: invalid reference format

### ISSUE THREAD

**Issue by ideivitcom** [Netflix/metaflow-tools#6]
Hi
Testing the 05 tutorial i have found a problem with (i think) the docker step.
In the attached image we can see that exist a problem with the docker image result of execute python 05-helloaws/helloaws.py run

I have configured with metaflow configure aws
The configuration:
{ 
   "METAFLOW_DEFAULT_DATASTORE":"s3",
   "METAFLOW_DATASTORE_SYSROOT_S3":"s3://stackmetaflow-metaflows3bucket-[REMOVED_BY_SECURITY]/metaflow",
   "METAFLOW_DATATOOLS_SYSROOT_S3":"s3://stackmetaflow-metaflows3bucket-[REMOVED_BY_SECURITY]/metaflow/data",
   "METAFLOW_BATCH_JOB_QUEUE":"arn:aws:batch:us-west-2:[REMOVED_BY_SECURITY]:job-queue/job-queue-stackMetaflow",
   "METAFLOW_BATCH_CONTAINER_IMAGE":"3.9.0a2-alpine3.10",
   "METAFLOW_BATCH_CONTAINER_REGISTRY":"https://index.docker.io/v1/",
   "METAFLOW_ECS_S3_ACCESS_IAM_ROLE":"arn:aws:iam::[REMOVED_BY_SECURITY]6:role/stackMetaflow-BatchS3TaskRole-[REMOVED_BY_SECURITY]",
   "METAFLOW_DEFAULT_METADATA":"service",
   "METADATA_SERVICE_URL":"https://[REMOVED_BY_SECURITY].execute-api.us-west-2.amazonaws.com/api/"
}
Although it says in the documentation that both: Container and hub are optional, the config tool requires both.

I suppose that the configurator demands the tag of python image.

The hub have been obtainer from the command: docker info
![image](https://user-images.githubusercontent.com/48516073/71362500-8a125200-2596-11ea-8559-6d137f6ac533.png)

![image](https://user-images.githubusercontent.com/48516073/71362100-6ac6f500-2595-11ea-8da7-ac36c3ae98ae.png)

**Comment by savingoyal** [comment]
Please use metaflow v2.0.1 and reconfigure using ‘metaflow configure aws’.
