### ISSUE TITLE
CloudFormation template failure: Invalid IamInstanceProfile: ecsInstanceRole

### ISSUE THREAD

**Issue by kevhill** [Netflix/metaflow-tools#9]
Attempting to run the template produces an error on a brand new AWS account. The error is 

```Operation failed, ComputeEnvironment went INVALID with error: CLIENT_ERROR - Invalid IamInstanceProfile: ecsInstanceRole```

when attempting to set up the `ComputeEnvironment` with batch. googling lead me to this question

https://stackoverflow.com/questions/46265278/aws-batch-client-error-invalid-iaminstanceprofile

Which indicated that the `Instance Role:` setting needs to reference a `AWS::IAM::InstanceProfile` rather than a `AWS::IAM::Role`

following the advice there and adding an :InstanceProfile that referenced that role seems to have worked

```  BatchInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: '/'
            Roles:
                - !Ref BatchExecutionRole
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: !GetAtt 'BatchExecutionRole.Arn'
      ComputeEnvironmentName: !Join [ "-", [ 'batch-compute-env', !Ref 'AWS::StackName' ] ]
      ComputeResources:
        MaxvCpus: !Ref MaxVCPUBatch
        SecurityGroupIds:
          - !Ref SagemakerSecurityGroup
        Type: EC2
        Subnets:
          - !Ref Subnet1
          - !Ref Subnet2
        MinvCpus: !Ref MinVCPUBatch
        InstanceRole: !GetAtt BatchInstanceProfile.Arn
        InstanceTypes:
          - c4.large
          - c4.xlarge
          - c4.2xlarge
          - c4.4xlarge
          - c4.8xlarge
        DesiredvCpus: !Ref DesiredVCPUBatch
      State: ENABLED
```

However, given my relative inexperience with cloudformation I figured I would bring this up as an issue instead of a pr

**Comment by savingoyal** [comment]
You would need to create an `ecsInstanceRole` as specified in the pre-requisites here - https://github.com/Netflix/metaflow-tools/tree/master/aws/cloudformation#prerequisites

**Comment by kevhill** [comment]
yup, reading hard
